"""empty message

Revision ID: 69381017a676
Revises: dca4fd2020a2
Create Date: 2020-09-03 20:59:19.530400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69381017a676'
down_revision = 'dca4fd2020a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
