"""empty message

Revision ID: 8bebf589c9f2
Revises: f30893a27d3d
Create Date: 2020-09-02 18:35:42.620041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bebf589c9f2'
down_revision = 'f30893a27d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'buying_power')
    op.add_column('user', sa.Column('buying_power', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'buying_power')
    op.add_column('portfolio', sa.Column('buying_power', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
