"""empty message

Revision ID: dca4fd2020a2
Revises: 8bebf589c9f2
Create Date: 2020-09-02 19:24:21.569370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca4fd2020a2'
down_revision = '8bebf589c9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('transaction', sa.Column('shares', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'shares')
    op.drop_column('transaction', 'price')
    # ### end Alembic commands ###
