"""empty message

Revision ID: f30893a27d3d
Revises: c17fb04d1c5d
Create Date: 2020-09-02 18:29:52.119230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30893a27d3d'
down_revision = 'c17fb04d1c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('buying_power', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'buying_power')
    # ### end Alembic commands ###
